[project]
name = "rag-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chroma>=0.2.0",
    "docling",
    "fastapi>=0.140.0",
    "markdownify>=1.2.3",
    "pandas>=2.3.3",
    "python-docx>=1.2.0",
    "sentence-transformers>=5.6.1",
    "tenacity>=9.1.4",
    "uvicorn>=0.51.0",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true
